---
name: "Lint"
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: "Lint Everything"
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - uses: "bewuethr/yamllint-action@v3"
        with:
          config-file: ".yamllint"
      - uses: "nosborn/github-action-markdown-cli@v3.3.0"
        with:
          files: "."
          config_file: ".markdownlint.yaml"
  spellcheck:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@v0
